fix(dynamodb): ensure table is ready
winglang/winglibs pull request #178
Opened 2024-04-03 07:40 UTC by skyrpex

Use the DescribeTable operation on a table to ensure that the table is ready.

2024-04-03 08:47 UTC, eladb requested changes

2024-04-03 08:47 UTC, eladb commented on dynamodb/dynamodb.sim.w
> +            client.describeTable({
If the table is not ready, this will throw. I believe you need to try/catch and return false.

2024-04-05 00:31 UTC, Chriscbr approved these changes

2024-04-05 00:37 UTC, Chriscbr commented on dynamodb/dynamodb.sim.w
You'l have to bump package.json until we're able to automate it

2024-04-08 11:18 UTC, eladb approved these changes

2024-04-08 11:21 UTC, merged